"""
Chatterbox gRPC TTS Plugin for LiveKit Agents

Custom TTS plugin using gRPC streaming for low-latency text-to-speech
with custom voice cloning (HAL 9000, C-3PO).

Author: C-3PO Team
Date: 2026-01-02
"""
import asyncio
import logging
import grpc
from typing import Optional
from livekit.agents import tts, utils, APIConnectionError, APIStatusError, APITimeoutError
from livekit.agents.types import DEFAULT_API_CONNECT_OPTIONS, APIConnectOptions

# Import generated Protocol Buffers stubs
# These will be generated by generate_protos.sh in the chatterbox-tts container
# Import Protocol Buffers stubs - handle both package and subprocess contexts
import sys
import os

# Add plugins directory to path for subprocess imports
_plugins_dir = os.path.dirname(os.path.abspath(__file__))
if _plugins_dir not in sys.path:
    sys.path.insert(0, _plugins_dir)

try:
    # Try relative import first (package context)
    from . import chatterbox_pb2
    from . import chatterbox_pb2_grpc
except ImportError:
    try:
        # Fallback to absolute import (subprocess context)
        import chatterbox_pb2
        import chatterbox_pb2_grpc
    except ImportError as e:
        logger = logging.getLogger(__name__)
        logger.error(
            f"Failed to import Chatterbox protobuf stubs: {e}\n"
            "Ensure chatterbox_pb2.py and chatterbox_pb2_grpc.py are in plugins directory"
        )
        raise

logger = logging.getLogger(__name__)


class ChatterboxGRPCTTS(tts.TTS):
    """
    Chatterbox gRPC TTS plugin for LiveKit Agents.

    Uses gRPC streaming for low-latency text-to-speech synthesis with
    custom voice cloning (HAL 9000, C-3PO, Barry).

    Implements LiveKit TTS interface with:
    - synthesize(): Text → ChunkedStream
    - Streaming support via gRPC (500ms chunks)

    Voice files:
    - c3po_short_30s_44k.wav: C-3PO voice (17.76s, 44.1kHz)
    - hal_combined_44k.wav: HAL 9000 voice (74.14s, 44.1kHz)
    - barry_combined_44k.wav: Barry voice (88.87s, 44.1kHz)

    Performance:
    - First byte: ~300ms (vs 800ms HTTP)
    - Total latency: ~2-2.5s
    - Binary protocol: Lower overhead than HTTP
    """

    def __init__(
        self,
        host: str = "chatterbox-tts-chatterbox-tts-server-1",
        port: int = 50051,
        voice: str = "hal_combined_44k.wav",
        sample_rate: int = 44100,
        language: str = "fr",
        temperature: float = 0.7,
        speed_factor: float = 1.0,
    ):
        """
        Initialize Chatterbox gRPC TTS plugin.

        Args:
            host: gRPC server host
            port: gRPC server port (50051)
            voice: Voice filename (c3po_short_30s_44k.wav, hal_combined_44k.wav)
            sample_rate: Output sample rate (44100 recommended)
            language: Language code (fr, en, es)
            temperature: Voice temperature 0.0-1.0
            speed_factor: Speech speed multiplier
        """
        super().__init__(
            capabilities=tts.TTSCapabilities(
                streaming=True  # gRPC supports streaming
            ),
            sample_rate=sample_rate,
            num_channels=1
        )

        self.host = host
        self.port = port
        self.voice = voice
        self.language = language
        self.temperature = temperature
        self.speed_factor = speed_factor
        self._channel: Optional[grpc.aio.Channel] = None

        logger.info(
            f"ChatterboxGRPCTTS initialized: voice={voice}, "
            f"sample_rate={sample_rate}Hz, language={language}, "
            f"server={host}:{port}"
        )

    @property
    def model(self) -> str:
        return "chatterbox-multilingual-grpc"

    @property
    def provider(self) -> str:
        return "ChatterboxGRPC"

    async def _ensure_channel(self) -> grpc.aio.Channel:
        """Ensure gRPC channel is open."""
        if not self._channel:
            self._channel = grpc.aio.insecure_channel(
                f"{self.host}:{self.port}",
                options=[
                    ('grpc.max_send_message_length', 50 * 1024 * 1024),
                    ('grpc.max_receive_message_length', 50 * 1024 * 1024),
                    ('grpc.keepalive_time_ms', 10000),
                    ('grpc.keepalive_timeout_ms', 5000),
                ]
            )
            logger.debug(f"gRPC channel opened to {self.host}:{self.port}")
        return self._channel

    async def aclose(self) -> None:
        """Close gRPC channel on shutdown."""
        if self._channel:
            await self._channel.close()
            logger.debug("gRPC channel closed")

    def stream(
        self,
        *,
        conn_options: APIConnectOptions = DEFAULT_API_CONNECT_OPTIONS,
    ) -> "ChatterboxSynthesizeStream":
        """
        Create a streaming TTS session for voice.Agent.

        Returns:
            ChatterboxSynthesizeStream instance
        """
        return ChatterboxSynthesizeStream(tts=self, conn_options=conn_options)

    def synthesize(
        self,
        text: str,
        *,
        conn_options: APIConnectOptions = DEFAULT_API_CONNECT_OPTIONS,
    ) -> "ChatterboxGRPCChunkedStream":
        """
        Synthesize text to audio using gRPC streaming.

        Args:
            text: Text to synthesize
            conn_options: API connection options

        Returns:
            ChatterboxGRPCChunkedStream instance
        """
        return ChatterboxGRPCChunkedStream(
            tts=self,
            input_text=text,
            conn_options=conn_options,
        )


class ChatterboxGRPCChunkedStream(tts.ChunkedStream):
    """Synthesize text to speech using Chatterbox gRPC streaming."""

    def __init__(
        self,
        *,
        tts: ChatterboxGRPCTTS,
        input_text: str,
        conn_options: APIConnectOptions,
    ) -> None:
        super().__init__(tts=tts, input_text=input_text, conn_options=conn_options)
        self._tts: ChatterboxGRPCTTS = tts

    async def _run(self, output_emitter: tts.AudioEmitter) -> None:
        """
        Execute TTS synthesis via gRPC streaming and emit audio frames.

        Args:
            output_emitter: AudioEmitter to push audio data to
        """
        # Get gRPC channel and create stub
        channel = await self._tts._ensure_channel()
        stub = chatterbox_pb2_grpc.ChatterboxTTSStub(channel)

        # Create synthesis request
        request = chatterbox_pb2.SynthesizeRequest(
            text=self._input_text,
            voice=self._tts.voice,
            language=self._tts.language,
            temperature=self._tts.temperature,
            speed_factor=self._tts.speed_factor,
            sample_rate=self._tts.sample_rate,
            format=chatterbox_pb2.AudioFormat.PCM_16,
            stream=True
        )

        logger.debug(
            f"Chatterbox gRPC TTS request: voice={self._tts.voice}, "
            f"text_len={len(self._input_text)}, stream=True"
        )

        try:
            # Initialize output emitter
            output_emitter.initialize(
                request_id=utils.shortuuid(),
                sample_rate=self._tts.sample_rate,
                num_channels=1,
                mime_type="audio/pcm",
            )

            # Call streaming RPC
            stream = stub.SynthesizeStream(
                request,
                timeout=30.0
            )

            total_bytes = 0
            chunk_count = 0

            # Stream audio chunks
            async for audio_chunk in stream:
                if audio_chunk.audio_data:
                    # Push PCM audio bytes directly
                    output_emitter.push(audio_chunk.audio_data)
                    total_bytes += len(audio_chunk.audio_data)
                    chunk_count += 1

                    logger.debug(
                        f"Received chunk {audio_chunk.chunk_index}: "
                        f"{len(audio_chunk.audio_data)} bytes, "
                        f"{audio_chunk.duration_ms}ms, "
                        f"final={audio_chunk.is_final}"
                    )

                if audio_chunk.is_final:
                    logger.info(
                        f"✓ TTS completed: {total_bytes} bytes "
                        f"({chunk_count} chunks, "
                        f"{total_bytes / (self._tts.sample_rate * 2):.2f}s audio)"
                    )
                    break

            # Flush final audio
            output_emitter.flush()

        except grpc.aio.AioRpcError as e:
            if e.code() == grpc.StatusCode.DEADLINE_EXCEEDED:
                logger.error("gRPC TTS timeout")
                raise APITimeoutError() from e
            elif e.code() == grpc.StatusCode.UNAVAILABLE:
                logger.error(f"Chatterbox gRPC service unavailable: {e.details()}")
                raise APIConnectionError() from e
            else:
                logger.error(f"gRPC TTS error: {e.code()} - {e.details()}")
                raise APIStatusError(
                    message=f"Chatterbox gRPC TTS failed: {e.details()}",
                    status_code=e.code().value[0],
                    request_id=None,
                    body=None,
                ) from e

        except Exception as e:
            logger.error(f"TTS synthesis error: {e}", exc_info=True)
            raise


class ChatterboxSynthesizeStream(tts.SynthesizeStream):
    """
    Streaming TTS interface for voice.Agent (reads from input queue).

    This is required by voice.Agent which uses stream() instead of synthesize().
    """

    def __init__(
        self,
        *,
        tts: ChatterboxGRPCTTS,
        conn_options: APIConnectOptions,
    ) -> None:
        super().__init__(tts=tts, conn_options=conn_options)
        self._tts = tts

    async def _run(self, output_emitter: tts.AudioEmitter) -> None:
        """
        Process text chunks from input queue and synthesize to audio.

        Reads from self._input_ch (populated by voice.Agent) and generates
        audio for each text chunk using gRPC streaming.

        Args:
            output_emitter: Audio emitter for output frames
        """
        # Initialize emitter ONCE at the start
        emitter_initialized = False

        # Get gRPC channel
        channel = await self._tts._ensure_channel()
        stub = chatterbox_pb2_grpc.ChatterboxTTSStub(channel)

        # Process text chunks from the input channel
        async for text_chunk in self._input_ch:
            # Skip flush sentinels
            if isinstance(text_chunk, self._FlushSentinel):
                continue

            # Skip empty text
            if not text_chunk or not text_chunk.strip():
                continue

            logger.debug(f"SynthesizeStream: processing text '{text_chunk[:50]}...'")

            # Create synthesis request
            request = chatterbox_pb2.SynthesizeRequest(
                text=text_chunk,
                voice=self._tts.voice,
                language=self._tts.language,
                temperature=self._tts.temperature,
                speed_factor=self._tts.speed_factor,
                sample_rate=self._tts.sample_rate,
                format=chatterbox_pb2.AudioFormat.PCM_16,
                stream=True
            )

            try:
                # Initialize emitter on first audio
                if not emitter_initialized:
                    output_emitter.initialize(
                        request_id=utils.shortuuid(),
                        sample_rate=self._tts.sample_rate,
                        num_channels=1,
                        mime_type="audio/pcm",
                    )
                    emitter_initialized = True

                # Stream audio chunks
                stream = stub.SynthesizeStream(request, timeout=30.0)
                async for audio_chunk in stream:
                    if audio_chunk.audio_data:
                        output_emitter.push(audio_chunk.audio_data)
                    if audio_chunk.is_final:
                        break

            except grpc.aio.AioRpcError as e:
                logger.error(f"gRPC TTS error: {e.code()} - {e.details()}")
                continue  # Try next chunk
            except Exception as e:
                logger.error(f"TTS synthesis error: {e}")
                continue

        # Flush at the end
        if emitter_initialized:
            output_emitter.flush()
