# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

# Handle both package and subprocess import contexts
try:
    from . import chatterbox_pb2 as chatterbox__pb2
except ImportError:
    import chatterbox_pb2 as chatterbox__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in chatterbox_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChatterboxTTSStub(object):
    """Service de synthèse vocale streaming
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SynthesizeStream = channel.unary_stream(
                '/chatterbox.ChatterboxTTS/SynthesizeStream',
                request_serializer=chatterbox__pb2.SynthesizeRequest.SerializeToString,
                response_deserializer=chatterbox__pb2.AudioChunk.FromString,
                _registered_method=True)
        self.Synthesize = channel.unary_unary(
                '/chatterbox.ChatterboxTTS/Synthesize',
                request_serializer=chatterbox__pb2.SynthesizeRequest.SerializeToString,
                response_deserializer=chatterbox__pb2.AudioResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/chatterbox.ChatterboxTTS/Ping',
                request_serializer=chatterbox__pb2.PingRequest.SerializeToString,
                response_deserializer=chatterbox__pb2.PingResponse.FromString,
                _registered_method=True)


class ChatterboxTTSServicer(object):
    """Service de synthèse vocale streaming
    """

    def SynthesizeStream(self, request, context):
        """Synthèse avec streaming (audio chunks progressifs)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Synthesize(self, request, context):
        """Synthèse complète (retourne tout l'audio d'un coup)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatterboxTTSServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SynthesizeStream': grpc.unary_stream_rpc_method_handler(
                    servicer.SynthesizeStream,
                    request_deserializer=chatterbox__pb2.SynthesizeRequest.FromString,
                    response_serializer=chatterbox__pb2.AudioChunk.SerializeToString,
            ),
            'Synthesize': grpc.unary_unary_rpc_method_handler(
                    servicer.Synthesize,
                    request_deserializer=chatterbox__pb2.SynthesizeRequest.FromString,
                    response_serializer=chatterbox__pb2.AudioResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=chatterbox__pb2.PingRequest.FromString,
                    response_serializer=chatterbox__pb2.PingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chatterbox.ChatterboxTTS', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chatterbox.ChatterboxTTS', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatterboxTTS(object):
    """Service de synthèse vocale streaming
    """

    @staticmethod
    def SynthesizeStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/chatterbox.ChatterboxTTS/SynthesizeStream',
            chatterbox__pb2.SynthesizeRequest.SerializeToString,
            chatterbox__pb2.AudioChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Synthesize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chatterbox.ChatterboxTTS/Synthesize',
            chatterbox__pb2.SynthesizeRequest.SerializeToString,
            chatterbox__pb2.AudioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chatterbox.ChatterboxTTS/Ping',
            chatterbox__pb2.PingRequest.SerializeToString,
            chatterbox__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
