# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chatterbox.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chatterbox.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63hatterbox.proto\x12\nchatterbox\"\xbb\x01\n\x11SynthesizeRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05voice\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\x12\x13\n\x0btemperature\x18\x04 \x01(\x02\x12\x14\n\x0cspeed_factor\x18\x05 \x01(\x02\x12\x13\n\x0bsample_rate\x18\x06 \x01(\x05\x12\'\n\x06\x66ormat\x18\x07 \x01(\x0e\x32\x17.chatterbox.AudioFormat\x12\x0e\n\x06stream\x18\x08 \x01(\x08\"q\n\nAudioChunk\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x13\n\x0b\x63hunk_index\x18\x02 \x01(\x05\x12\x10\n\x08is_final\x18\x03 \x01(\x08\x12\x13\n\x0bsample_rate\x18\x04 \x01(\x05\x12\x13\n\x0b\x64uration_ms\x18\x05 \x01(\x05\"v\n\rAudioResponse\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\x12\x13\n\x0b\x64uration_ms\x18\x03 \x01(\x05\x12\'\n\x06\x66ormat\x18\x04 \x01(\x0e\x32\x17.chatterbox.AudioFormat\"\r\n\x0bPingRequest\"/\n\x0cPingResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t*+\n\x0b\x41udioFormat\x12\n\n\x06PCM_16\x10\x00\x12\x07\n\x03WAV\x10\x01\x12\x07\n\x03MP3\x10\x02\x32\xdf\x01\n\rChatterboxTTS\x12K\n\x10SynthesizeStream\x12\x1d.chatterbox.SynthesizeRequest\x1a\x16.chatterbox.AudioChunk0\x01\x12\x46\n\nSynthesize\x12\x1d.chatterbox.SynthesizeRequest\x1a\x19.chatterbox.AudioResponse\x12\x39\n\x04Ping\x12\x17.chatterbox.PingRequest\x1a\x18.chatterbox.PingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chatterbox_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOFORMAT']._serialized_start=521
  _globals['_AUDIOFORMAT']._serialized_end=564
  _globals['_SYNTHESIZEREQUEST']._serialized_start=33
  _globals['_SYNTHESIZEREQUEST']._serialized_end=220
  _globals['_AUDIOCHUNK']._serialized_start=222
  _globals['_AUDIOCHUNK']._serialized_end=335
  _globals['_AUDIORESPONSE']._serialized_start=337
  _globals['_AUDIORESPONSE']._serialized_end=455
  _globals['_PINGREQUEST']._serialized_start=457
  _globals['_PINGREQUEST']._serialized_end=470
  _globals['_PINGRESPONSE']._serialized_start=472
  _globals['_PINGRESPONSE']._serialized_end=519
  _globals['_CHATTERBOXTTS']._serialized_start=567
  _globals['_CHATTERBOXTTS']._serialized_end=790
# @@protoc_insertion_point(module_scope)
